quarkus:

#  rest-client:
#    logging:
#      scope: request-response
#
#  log:
#    category:
#      "org.jboss.resteasy.reactive.client.logging":
#        level: DEBUG

  flyway:
    clean-at-start: true

  http:
    port: 8080

    cors:
      enabled: true
      origins: "http://localhost:5173"

  security:
    auth:
      enabled-in-dev-mode: false

app:
  memrise:
    access-token: ${MEMRISE_TOKEN}